package Checked_Exception_Handling;

public class Exception_Handling {

	public static void main(String[] args) {
		int array[] = {20,20,40};
		int num1 = 15, num2 = 0;
		int result = 0;
		try {
			result = num1 / num2;
			System.out.println("The Result is " + result);
			for(int i=2; i>=0; i--) {
				System.out.println("The value of the array is "+array[i]);
			}
		} catch (ArrayIndexOutOfBoundsException abe) {
			System.out.println("Error Array is out of bound "+abe);
		}
		catch (ArithmeticException ae) {
			System.out.println("Can not devided by zero "+ae);
		}

	}

}
